#define DAY_IN_SECONDS                86400

#define CYCLE_1_DURATION              18 * DAY_IN_SECONDS
#define CYCLE_1_TEMPERATURE_MIN       37.2
#define CYCLE_1_TEMPERATURE_OPTIMAL   37.5
#define CYCLE_1_TEMPERATURE_MAX       38.9
#define CYCLE_1_HUMIDITY_MIN          50.0
#define CYCLE_1_HUMIDITY_OPTIMAL      60.0
#define CYCLE_1_HUMIDITY_MAX          65.0
#define CYCLE_1_TURN_EVERY            30
#define CYCLE_1_TURN_FOR              20
#define CYCLE_1_TURN_DIRECTION_STEPS  1

#define CYCLE_2_DURATION              3.25 * DAY_IN_SECONDS
#define CYCLE_2_TEMPERATURE_MIN       CYCLE_1_TEMPERATURE_MIN
#define CYCLE_2_TEMPERATURE_OPTIMAL   CYCLE_1_TEMPERATURE_OPTIMAL
#define CYCLE_2_TEMPERATURE_MAX       CYCLE_1_TEMPERATURE_MAX
#define CYCLE_2_HUMIDITY_MIN          70.0
#define CYCLE_2_HUMIDITY_OPTIMAL      75.0
#define CYCLE_2_HUMIDITY_MAX          80.0
#define CYCLE_2_TURN_EVERY            10
#define CYCLE_2_TURN_FOR              0
#define CYCLE_2_TURN_DIRECTION_STEPS  1
